# Sonuç {-}  
Bu çalışmada KTS ciddiyet sınıflandırması için makine öğrenmesi yöntemleri kullanılmıştır. Çalışmada Güney Kore’deki bir hastanede yapılan çalışmadan elde edilen ve üç farklı ciddiyet sınıfına sahip ("Mild", "Moderate", "Severe") 1037 el örneği [@park2021machine]  üzerinde KTS ciddiyet düzeylerinin tahminlenmesi amacı ile farklı sınıflama modelleri kurulmuş olup bu modellerin kendi aralarında değerlendirmesi yapılmıştır.  

\  

Uygulamanın ilk bölümünde (\ref{multiclass}) üç sınıflı sınıflandırma problemi için K-En yakın komşuluk, rassal ormanlar, yapay sinir ağları ve XGBoost algoritmaları kullanılmıştır ve %73 doğru sınıflandırma oranı ile en iyi sonuçlar XGBoost algoritması ile elde edilmiştir. Uygulamanın ikinci bölümünde (\ref{binary}) doğru sınıflandırma oranını arttırabilmek amacı ile "Mild" ve "Moderate + Severe" olacak şekilde problem iki sınıflı sınıflandırmaya indirgenmiştir. Uygulamanın ikinci bölümünde (\ref{binary}) veri seti üç sınıflıdan iki sınıflıya indirgenmesi ile doğruluk oranlarında ve diğer sınıflama metriklerinde ciddi artışlar gerçekleşmiş ve iki sınıflı problemde XGBoost algoritması KTS ciddiyet skorlarını %82 oranında doğru sınıflandırmaktadır. 

\

Çalışmanın sonuçlarına göre KTS ciddiyet skorlarının sınıflanmasında, girişimsel testlerin maddi, manevi ve zaman kayıpları göz önüne alındığında hastaların bir takım acılı girişimsel testlerden geçmesine engel olabilmek amacı ile makine öğrenmesi yöntemlerinin kullanılabileceği öngörülmektedir. Sonraki çalışmalarda kurulan modelleri temel alan ve hastadan elde edilen verilere göre ciddiyet sınıflaması yapan mobil ya da web uygulamaları düşünülebilir. 


<!--**More info**

And here's some other random info: the first paragraph after a chapter title or section head _shouldn't be_ indented, because indents are to tell the reader that you're starting a new paragraph. Since that's obvious after a chapter or section title, proper typesetting doesn't add an indent there.
-->


